import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HamburgerMenu from "@/components/HamburgerMenu";
import { client } from "@/lib/contentful";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getPages() {
  const entries = await client.getEntries({ content_type: 'playbookInnerPage' });
  return entries.items.map((item: any) => ({
    title: item.fields.title,
    slug: item.fields.slug,
  }));
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pages = await getPages();

  return (
    <html lang="en">
      <body className={inter.className}>
        <HamburgerMenu pages={pages} />
        {children}
      </body>
    </html>
  );
}
