import type { Metadata } from "next";
import "./globals.css";
import HamburgerMenu from "@/components/HamburgerMenu";
import { client } from "@/lib/contentful";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getPages() {
  try {
    const entries = await client.getEntries({
      content_type: 'playbookInnerPage'
    });
    console.log('Complete Contentful Response:', JSON.stringify(entries, null, 2));
    return entries.items.map((item: any) => {
      if (!item.fields.title) {
        console.warn('Entry missing title:', item);
      }
      const page = {
        title: item.fields.title || 'Untitled',
        slug: item.fields.slug || 'no-slug',
        fields: {
          body: item.fields.body,
          description: item.fields.description,
          audioFile: item.fields.audioFile,
          commonPitfalls: item.fields.commonPitfalls,
          additionalResources: item.fields.additionalResources
        }
      };
      return page;
    });
  } catch (error) {
    console.error('Contentful error:', error);
    return [];
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pages = await getPages();

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,100..900;1,100..900&family=Be+Vietnam+Pro:wght@500&display=swap" rel="stylesheet" />
      </head>
      <body className="font-sans bg-paper text-ink min-h-screen bg-paper-texture">
        <HamburgerMenu pages={pages} />
        {children}
      </body>
    </html>
  );
}
